### PR TITLE
Fix: privacy plugin noop on mobile

### LINKED ISSUE #706: [Not Working] - "Privacy view on intel" Offical Plugin
After new update release (IITC Mobile v0.38.0), "Privacy view on intel" Plugin not working anymore.

IITC Mobile app > Plugins > Official Plugins > MISC > Privacy view on intel
Screenshot_2024-02-24-10-05-23-33_4bd081dab89a3c82e75a2ae7696e5187

Privacy Active - nothing changed
Screenshot_2024-02-24-10-03-21-54_4bd081dab89a3c82e75a2ae7696e5187~2

Privacy Inactive - nothing changed
Screenshot_2024-02-24-10-03-24-12_4bd081dab89a3c82e75a2ae7696e5187~2

### PR DESCRIPTION
**Pull request by le-jeu**
fix #706

### CODE REVIEW

**Review by xscreach — APPROVED** [review]

File: plugins/privacy-view.js [hunk 1]
```diff
@@ -32,9 +32,10 @@ privacyView.toggle = () => {
   privacyView.is_active = !privacyView.is_active;
   if (window.isSmartphone()) {
     IITC.toolbox.updateButton('privacytoggle', { label: privacyView.text[privacyView.is_active] });
+    document.body.classList.toggle('privacy_active');
```
Comment (modos189) [inline plugins/privacy-view.js]: This toggle is the same for mobile and desktop, it is better to put it after line 32

**Review by modos189 — APPROVED** [review]
