### PR TITLE
Fix：Hack Cooldown Time in Portal info panel enhanced

### LINKED ISSUE #534: Hacktime is not shown correctly
The cooldown timer within IITC is still set to 5 minutes in portal view,even though it's been 2,5 minutes for a while

2021-08-27_22h46_59

### PR DESCRIPTION
**Pull request by ODBLK**
According to "https://ingress.com/news/q4-2022-tempchanges/":
> The following temporary change will return to its original value, effective starting Friday, September 30:
> Portal cooldown between hacks will be reverted to its original value of 300 seconds on neutral Portals and Portals aligned to the opposite Faction, up from 90 seconds.
> Portal cooldown between hacks will be 180 seconds on Portals aligned to the Agents’ Faction, up from 90 seconds

Modify the basic calculation value of the relevant information in the Portal info panel

Fix: #534

### CODE REVIEW

**Review by modos189 — APPROVED** [review]

File: core/code/portal_info.js [hunk 1]
```diff
@@ -349,7 +349,8 @@ window.getPortalHackDetails = function (d) {
   // first mod of type is fully effective, the others are only 50% effective
   var effectivenessReduction = [1, 0.5, 0.5, 0.5];
 
-  var cooldownTime = window.BASE_HACK_COOLDOWN;
+  var isFriendly = window.teamStringToId(d.team) === window.teamStringToId(window.PLAYER.team);
```
Comment (johnd0e) [inline core/code/portal_info.js:352]: teamStringToId calls are redundant.

Comment (McBen) [reply core/code/portal_info.js:352]: > teamStringToId calls are redundant.

`portailDetails.team = "R"`

`window.PLAYER.team = "RESISTANCE"`

no, it's not redundant
